In [24]:
import soccerdata as sd

fbref = sd.FBref(leagues='ENG-Premier League', seasons='2024-25')
stats = fbref.read_player_season_stats(stat_type='standard')
stats.head()

[09/13/26 17:50:04] INFO     Saving cached data to C:\Users\pryde\soccerdata\data\FBref              ]8;id=7889905;file://C:\Users\pryde\Documents\Football\Analysis\football-analytics\venv\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=7889906;file://C:\Users\pryde\Documents\Football\Analysis\football-analytics\venv\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

                                                nation    pos age  born  \

league             season team    player
ENG-Premier League 2425   Arsenal Ben White        ENG     DF  26  1997
                                  Bukayo Saka      ENG  FW,MF  22  2001
                                  David Raya       ESP     GK  28  1995
                                  Declan Rice      ENG     MF  25  1999
                                  Ethan Nwaneri    ENG  FW,MF  17  2007

                                                Playing Time               \
                                                          MP Starts   Min
league             season team    player
ENG-Premier League 2425   Arsenal Ben White               17     13  1198
                                  Bukayo Saka             25     20  1729
                                  David Raya              38     38  3420
                                  Declan Rice             35     33  2825
                                  Ethan Nwaneri           26     11   895

                                                      Performance      ...  \
                                                  90s         Gls Ast  ...
league             season team    player                               ...
ENG-Premier League 2425   Arsenal Ben White      13.3           0   2  ...
                                  Bukayo Saka    19.2           6  10  ...
                                  David Raya     38.0           0   0  ...
                                  Declan Rice    31.4           4   7  ...
                                  Ethan Nwaneri   9.9           4   2  ...

                                                                         \
                                                G-PK PK PKatt CrdY CrdR
league             season team    player
ENG-Premier League 2425   Arsenal Ben White        0  0     0    2    0
                                  Bukayo Saka      5  1     1    3    0
                                  David Raya       0  0     0    3    0
                                  Declan Rice      4  0     0    7    1
                                  Ethan Nwaneri    4  0     0    1    0

                                                Per 90 Minutes              \
                                                           Gls   Ast   G+A
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                0.0  0.15  0.15
                                  Bukayo Saka             0.31  0.52  0.83
                                  David Raya               0.0   0.0   0.0
                                  Declan Rice             0.13  0.22  0.35
                                  Ethan Nwaneri            0.4   0.2   0.6


                                                 G-PK G+A-PK
league             season team    player
ENG-Premier League 2425   Arsenal Ben White       0.0   0.15
                                  Bukayo Saka    0.26   0.78
                                  David Raya      0.0    0.0
                                  Declan Rice    0.13   0.35
                                  Ethan Nwaneri   0.4    0.6

[5 rows x 21 columns]

In [25]:
stats.columns.tolist()

[('nation', ''),
 ('pos', ''),
 ('age', ''),
 ('born', ''),
 ('Playing Time', 'MP'),
 ('Playing Time', 'Starts'),
 ('Playing Time', 'Min'),
 ('Playing Time', '90s'),
 ('Performance', 'Gls'),
 ('Performance', 'Ast'),
 ('Performance', 'G+A'),
 ('Performance', 'G-PK'),
 ('Performance', 'PK'),
 ('Performance', 'PKatt'),
 ('Performance', 'CrdY'),
 ('Performance', 'CrdR'),
 ('Per 90 Minutes', 'Gls'),
 ('Per 90 Minutes', 'Ast'),
 ('Per 90 Minutes', 'G+A'),
 ('Per 90 Minutes', 'G-PK'),
 ('Per 90 Minutes', 'G+A-PK')]

In [26]:
stats.columns = ['_'.join(col).strip('_') for col in stats.columns]
stats.columns.tolist()

['nation',
 'pos',
 'age',
 'born',
 'Playing Time_MP',
 'Playing Time_Starts',
 'Playing Time_Min',
 'Playing Time_90s',
 'Performance_Gls',
 'Performance_Ast',
 'Performance_G+A',
 'Performance_G-PK',
 'Performance_PK',
 'Performance_PKatt',
 'Performance_CrdY',
 'Performance_CrdR',
 'Per 90 Minutes_Gls',
 'Per 90 Minutes_Ast',
 'Per 90 Minutes_G+A',
 'Per 90 Minutes_G-PK',
 'Per 90 Minutes_G+A-PK']

In [27]:
shooting = fbref.read_player_season_stats(stat_type='shooting')
misc = fbref.read_player_season_stats(stat_type='misc')

shooting.columns = ['_'.join(col).strip('_') for col in shooting.columns]
misc.columns = ['_'.join(col).strip('_') for col in misc.columns]

print(shooting.columns.tolist())
print(misc.columns.tolist())

['nation', 'pos', 'age', 'born', '90s', 'Standard_Gls', 'Standard_Sh', 'Standard_SoT', 'Standard_SoT%', 'Standard_Sh/90', 'Standard_SoT/90', 'Standard_G/Sh', 'Standard_G/SoT', 'Standard_PK', 'Standard_PKatt']
['nation', 'pos', 'age', 'born', '90s', 'Performance_CrdY', 'Performance_CrdR', 'Performance_2CrdY', 'Performance_Fls', 'Performance_Fld', 'Performance_Off', 'Performance_Crs', 'Performance_Int', 'Performance_TklW', 'Performance_PKwon', 'Performance_PKcon', 'Performance_OG']

In [28]:
merged = stats.merge(shooting, on=['league', 'season', 'team', 'player'], suffixes=('', '_shooting'))
merged = merged.merge(misc, on=['league', 'season', 'team', 'player'], suffixes=('', '_misc'))
print(merged.shape)
merged.head()

(574, 53)

                                                nation    pos  age  born  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White        ENG     DF   26  1997
                                  Bukayo Saka      ENG  FW,MF   22  2001
                                  David Raya       ESP     GK   28  1995
                                  Declan Rice      ENG     MF   25  1999
                                  Ethan Nwaneri    ENG  FW,MF   17  2007

                                                 Playing Time_MP  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                   17
                                  Bukayo Saka                 25
                                  David Raya                  38
                                  Declan Rice                 35
                                  Ethan Nwaneri               26

                                                 Playing Time_Starts  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                       13
                                  Bukayo Saka                     20
                                  David Raya                      38
                                  Declan Rice                     33
                                  Ethan Nwaneri                   11

                                                 Playing Time_Min  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                  1198
                                  Bukayo Saka                1729
                                  David Raya                 3420
                                  Declan Rice                2825
                                  Ethan Nwaneri               895

                                                 Playing Time_90s  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                  13.3
                                  Bukayo Saka                19.2
                                  David Raya                 38.0
                                  Declan Rice                31.4
                                  Ethan Nwaneri               9.9

                                                 Performance_Gls  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                    0
                                  Bukayo Saka                  6
                                  David Raya                   0
                                  Declan Rice                  4
                                  Ethan Nwaneri                4

                                                 Performance_Ast  ...  \
league             season team    player                          ...
ENG-Premier League 2425   Arsenal Ben White                    2  ...
                                  Bukayo Saka                 10  ...
                                  David Raya                   0  ...
                                  Declan Rice                  7  ...
                                  Ethan Nwaneri                2  ...

                                                 Performance_2CrdY  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                      0
                                  Bukayo Saka                    0
                                  David Raya                     0
                                  Declan Rice                    1
                                  Ethan Nwaneri                  0

                                                 Performance_Fls  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                   10
                                  Bukayo Saka                 15
                                  David Raya                   1
                                  Declan Rice                 21
                                  Ethan Nwaneri               10

                                                 Performance_Fld  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                    5
                                  Bukayo Saka                 39
                                  David Raya                  10
                                  Declan Rice                 16
                                  Ethan Nwaneri                5

                                                 Performance_Off  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                    1
                                  Bukayo Saka                  7
                                  David Raya                   0
                                  Declan Rice                  2
                                  Ethan Nwaneri                6

                                                 Performance_Crs  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                   17
                                  Bukayo Saka                115
                                  David Raya                   0
                                  Declan Rice                161
                                  Ethan Nwaneri               54

                                                 Performance_Int  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                   16
                                  Bukayo Saka                  3
                                  David Raya                   0
                                  Declan Rice                 27
                                  Ethan Nwaneri                3

                                                 Performance_TklW  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                    15
                                  Bukayo Saka                  15
                                  David Raya                    0
                                  Declan Rice                  23
                                  Ethan Nwaneri                 6

                                                 Performance_PKwon  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                   <NA>
                                  Bukayo Saka                 <NA>
                                  David Raya                  <NA>
                                  Declan Rice                 <NA>
                                  Ethan Nwaneri               <NA>

                                                 Performance_PKcon  \
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                   <NA>
                                  Bukayo Saka                 <NA>
                                  David Raya                  <NA>
                                  Declan Rice                 <NA>
                                  Ethan Nwaneri               <NA>

                                                 Performance_OG
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                   0
                                  Bukayo Saka                 0
                                  David Raya                  0
                                  Declan Rice                 0
                                  Ethan Nwaneri               0

[5 rows x 53 columns]

In [29]:
print(f"Original stats rows: {len(stats)}")
print(f"Merged rows: {len(merged)}")

Original stats rows: 574
Merged rows: 574

In [30]:
model_data = merged[merged['Playing Time_90s'] >= 10].copy()
model_data = model_data.reset_index()
print(f"Players with 10+ full matches worth of minutes: {len(model_data)}")

Players with 10+ full matches worth of minutes: 322

In [31]:
feature_cols = [
    'Standard_Gls', 'Standard_Sh', 'Standard_SoT%', 'Standard_G/Sh',
    'Performance_Ast', 'Performance_Crs', 'Performance_TklW',
    'Performance_Int', 'Performance_Fls', 'Performance_Fld'
]

In [32]:
per_90_needed = ['Standard_Gls', 'Standard_Sh', 'Performance_Ast', 'Performance_Crs',
                  'Performance_TklW', 'Performance_Int', 'Performance_Fls', 'Performance_Fld']

for col in per_90_needed:
    model_data[col + '_p90'] = model_data[col] / model_data['Playing Time_90s']

In [33]:
from sklearn.preprocessing import StandardScaler

final_features = ['Standard_Gls_p90', 'Standard_Sh_p90', 'Standard_SoT%', 'Standard_G/Sh',
                   'Performance_Ast_p90', 'Performance_Crs_p90', 'Performance_TklW_p90',
                   'Performance_Int_p90', 'Performance_Fls_p90', 'Performance_Fld_p90']

X = model_data[final_features].fillna(0)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [34]:
from sklearn.neighbors import NearestNeighbors

nn_model = NearestNeighbors(n_neighbors=6, metric='cosine')
nn_model.fit(X_scaled)

NearestNeighbors(metric='cosine', n_neighbors=6)

In [35]:
model_data.columns.tolist()

['league',
 'season',
 'team',
 'player',
 'nation',
 'pos',
 'age',
 'born',
 'Playing Time_MP',
 'Playing Time_Starts',
 'Playing Time_Min',
 'Playing Time_90s',
 'Performance_Gls',
 'Performance_Ast',
 'Performance_G+A',
 'Performance_G-PK',
 'Performance_PK',
 'Performance_PKatt',
 'Performance_CrdY',
 'Performance_CrdR',
 'Per 90 Minutes_Gls',
 'Per 90 Minutes_Ast',
 'Per 90 Minutes_G+A',
 'Per 90 Minutes_G-PK',
 'Per 90 Minutes_G+A-PK',
 'nation_shooting',
 'pos_shooting',
 'age_shooting',
 'born_shooting',
 '90s',
 'Standard_Gls',
 'Standard_Sh',
 'Standard_SoT',
 'Standard_SoT%',
 'Standard_Sh/90',
 'Standard_SoT/90',
 'Standard_G/Sh',
 'Standard_G/SoT',
 'Standard_PK',
 'Standard_PKatt',
 'nation_misc',
 'pos_misc',
 'age_misc',
 'born_misc',
 '90s_misc',
 'Performance_CrdY_misc',
 'Performance_CrdR_misc',
 'Performance_2CrdY',
 'Performance_Fls',
 'Performance_Fld',
 'Performance_Off',
 'Performance_Crs',
 'Performance_Int',
 'Performance_TklW',
 'Performance_PKwon',
 'Performance_PKcon',
 'Performance_OG',
 'Standard_Gls_p90',
 'Standard_Sh_p90',
 'Performance_Ast_p90',
 'Performance_Crs_p90',
 'Performance_TklW_p90',
 'Performance_Int_p90',
 'Performance_Fls_p90',
 'Performance_Fld_p90']

In [36]:
model_data = model_data.reset_index()
model_data.columns.tolist()

['index',
 'league',
 'season',
 'team',
 'player',
 'nation',
 'pos',
 'age',
 'born',
 'Playing Time_MP',
 'Playing Time_Starts',
 'Playing Time_Min',
 'Playing Time_90s',
 'Performance_Gls',
 'Performance_Ast',
 'Performance_G+A',
 'Performance_G-PK',
 'Performance_PK',
 'Performance_PKatt',
 'Performance_CrdY',
 'Performance_CrdR',
 'Per 90 Minutes_Gls',
 'Per 90 Minutes_Ast',
 'Per 90 Minutes_G+A',
 'Per 90 Minutes_G-PK',
 'Per 90 Minutes_G+A-PK',
 'nation_shooting',
 'pos_shooting',
 'age_shooting',
 'born_shooting',
 '90s',
 'Standard_Gls',
 'Standard_Sh',
 'Standard_SoT',
 'Standard_SoT%',
 'Standard_Sh/90',
 'Standard_SoT/90',
 'Standard_G/Sh',
 'Standard_G/SoT',
 'Standard_PK',
 'Standard_PKatt',
 'nation_misc',
 'pos_misc',
 'age_misc',
 'born_misc',
 '90s_misc',
 'Performance_CrdY_misc',
 'Performance_CrdR_misc',
 'Performance_2CrdY',
 'Performance_Fls',
 'Performance_Fld',
 'Performance_Off',
 'Performance_Crs',
 'Performance_Int',
 'Performance_TklW',
 'Performance_PKwon',
 'Performance_PKcon',
 'Performance_OG',
 'Standard_Gls_p90',
 'Standard_Sh_p90',
 'Performance_Ast_p90',
 'Performance_Crs_p90',
 'Performance_TklW_p90',
 'Performance_Int_p90',
 'Performance_Fls_p90',
 'Performance_Fld_p90']

In [37]:
def find_similar_players(player_name, n=5):
    idx = model_data[model_data['player'] == player_name].index
    if len(idx) == 0:
        return f"Player '{player_name}' not found."
    
    idx = idx[0]
    row_position = model_data.index.get_loc(idx)
    
    distances, indices = nn_model.kneighbors([X_scaled[row_position]])
    
    similar_players = model_data.iloc[indices[0][1:n+1]][['player', 'team', 'pos'] + final_features]
    return similar_players

find_similar_players('Bukayo Saka')

,player,team,pos,Standard_Gls_p90,Standard_Sh_p90,Standard_SoT%,Standard_G/Sh,Performance_Ast_p90,Performance_Crs_p90,Performance_TklW_p90,Performance_Int_p90,Performance_Fls_p90,Performance_Fld_p90
9,Leandro Trossard,Arsenal,FW,0.282686,2.54417,30.6,0.11,0.24735,2.826855,0.636042,0.353357,0.954064,1.625442
206,Sávio,Manchester City,"MF,FW",0.05102,2.806122,38.2,0.02,0.408163,4.285714,0.867347,0.204082,0.867347,1.428571
98,Eberechi Eze,Crystal Palace,MF,0.277778,3.541667,28.4,0.08,0.277778,3.819444,0.729167,0.347222,0.451389,1.770833
125,Adama Traoré,Fulham,MF,0.101523,1.979695,30.8,0.05,0.35533,5.076142,0.659898,0.050761,1.218274,1.624365
194,Jeremy Doku,Manchester City,"MF,FW",0.178571,1.72619,31.0,0.1,0.357143,3.511905,1.369048,0.178571,0.595238,1.964286

In [38]:
find_similar_players('Erling Haaland')

,player,team,pos,Standard_Gls_p90,Standard_Sh_p90,Standard_SoT%,Standard_G/Sh,Performance_Ast_p90,Performance_Crs_p90,Performance_TklW_p90,Performance_Int_p90,Performance_Fls_p90,Performance_Fld_p90
225,Alexander Isak,Newcastle,FW,0.751634,3.235294,46.5,0.23,0.196078,0.522876,0.163399,0.098039,0.915033,0.457516
101,Jean-Philippe Mateta,Crystal Palace,FW,0.47619,2.346939,47.8,0.2,0.068027,0.884354,0.408163,0.068027,0.918367,0.986395
242,Chris Wood,Nottingham,FW,0.607903,2.066869,51.5,0.29,0.091185,0.030395,0.151976,0.182371,0.759878,0.729483
59,Yoane Wissa,Brentford,FW,0.58642,2.777778,47.8,0.21,0.123457,0.58642,0.401235,0.246914,1.018519,1.574074
62,Danny Welbeck,Brighton,FW,0.425532,2.553191,40.0,0.17,0.170213,0.12766,0.680851,0.212766,0.468085,0.978723

In [39]:
find_similar_players('Declan Rice')

,player,team,pos,Standard_Gls_p90,Standard_Sh_p90,Standard_SoT%,Standard_G/Sh,Performance_Ast_p90,Performance_Crs_p90,Performance_TklW_p90,Performance_Int_p90,Performance_Fls_p90,Performance_Fld_p90
213,Christian Eriksen,Manchester Utd,MF,0.084746,1.271186,13.3,0.07,0.169492,7.118644,0.677966,0.59322,0.677966,0.254237
196,Kevin De Bruyne,Manchester City,"MF,FW",0.21164,3.015873,31.6,0.07,0.37037,7.619048,0.47619,0.37037,0.899471,0.952381
112,Dwight McNeil,Everton,MF,0.263158,1.578947,41.7,0.17,0.394737,6.842105,0.526316,0.394737,0.394737,1.184211
54,Mikkel Damsgaard,Brentford,MF,0.06192,1.083591,20.0,0.06,0.309598,4.551084,1.362229,0.897833,0.557276,0.835913
87,Pedro Neto,Chelsea,"MF,FW",0.15873,2.34127,28.8,0.07,0.238095,5.912698,0.396825,0.31746,0.833333,1.309524

## Conclusion

Built a player-similarity engine using 2024-25 Premier League data from 
FBref (322 players with 10+ full matches played), combining standard, 
shooting, and miscellaneous stat categories into 10 per-90 features 
covering attacking output, shot quality, and defensive contribution.

**Method:** features were standardized (z-scores) and compared using 
cosine similarity via k-nearest-neighbors, returning the 5 most similar 
players to any given input.

**Validation:** the model performs strongly for attacking players — 
Bukayo Saka's closest matches (Trossard, Sávio, Eze, Traoré, Doku) are all 
recognizable wide-attacker/dribbler profiles, and Erling Haaland's matches 
(Isak, Mateta, Wood, Wissa, Welbeck) are all high-efficiency penalty-box 
finishers. Both results align with genuine football intuition.

**Limitation:** defensive midfielder comparisons are less reliable. 
Declan Rice's closest matches skewed toward creative attacking midfielders 
rather than genuine ball-winners, likely because only two defensive 
metrics (tackles won, interceptions per 90) were available through 
FBref's data via `soccerdata`, versus a much richer set of attacking 
features. I confirmed this is a genuine data ceiling — `soccerdata`'s 
FBref wrapper does not expose a dedicated passing or defensive stat 
category for player-season stats (checked via the library's own 
documentation) — rather than an oversight in feature selection.